### ISSUE TITLE
2.7.9b files working on version

### ISSUE THREAD

**Issue by tudat-lan** [mauserzjeh/cod-asset-importer#10]
Hy thans your work for the first time.

Please send old version 2.7.9b files working on version Thanks.

By Gábor

**Comment by mauserzjeh** [comment]
Blender 2.79b is not supported anymore. You can download some older releases from here https://github.com/mauserzjeh/cod-asset-importer/releases which might support older blender versions, but I would heavily advise against using it (plus I don't really remember if it was even supported in v1.0). Upgrade to Blender ~4.0 and use the latest release. Its much faster and supports more assets.

**Comment by tudat-lan** [comment]
Hi, if you think we can talk in Hungarian. Anyway, the problem is that I get such errors when I import the addon, regardless of win7 or win11, the same problem loads the d3dcsp file, but not the xmodul and everything else. So it does nothing win11- latest blender phyton everything. And yet...

`brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
vehicle_opel_blitz_woodland_static  (xmodel) not found or some unhandled error o
ccured.
prop_bench_d  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
vehicle_africa_jeep_static  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak8  (xmodel) not found or some unhandled error occured.
prop_crate_dak7  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak9  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak8  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak9  (xmodel) not found or some unhandled error occured.
prop_crate_dak9  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak8  (xmodel) not found or some unhandled error occured.
prop_crate_dak7  (xmodel) not found or some unhandled error occured.
prop_crate_dak6  (xmodel) not found or some unhandled error occured.
prop_crate_dak9  (xmodel) not found or some unhandled error occured.
prop_crate_dak9  (xmodel) not found or some unhandled error occured.
prop_streetlamp_off  (xmodel) not found or some unhandled error occured.
prop_streetlamp_off  (xmodel) not found or some unhandled error occured.
prop_wooden_barrel1  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
brush_newgrass_triangularclump  (xmodel) not found or some unhandled error occur
ed.
furniture_plainchair  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
*1  (xmodel) not found or some unhandled error occured.
german_artillery_flak88_nm_destroy  (xmodel) not found or some unhandled error o
ccured.
german_artillery_flak88_nm  (xmodel) not found or some unhandled error occured.
fx  (xmodel) not found or some unhandled error occured.
*2  (xmodel) not found or some unhandled error occured.
*3  (xmodel) not found or some unhandled error occured.
*4  (xmodel) not found or some unhandled error occured.
*5  (xmodel) not found or some unhandled error occured.
*6  (xmodel) not found or some unhandled error occured.
*7  (xmodel) not found or some unhandled error occured.
*8  (xmodel) not found or some unhandled error occured.
*9  (xmodel) not found or some unhandled error occured.
*10  (xmodel) not found or some unhandled error occured.
*11  (xmodel) not found or some unhandled error occured.
caen_bush_full_01  (xmodel) not found or some unhandled error occured.
light_lantern_on  (xmodel) not found or some unhandled error occured.
furniture_bookshelves1  (xmodel) not found or some unhandled error occured.
prop_streetlamp_off  (xmodel) not found or some unhandled error occured.
caen_bush_full_01  (xmodel) not found or some unhandled error occured.
awning_desert_wood1  (xmodel) not found or some unhandled error occured.
*12  (xmodel) not found or some unhandled error occured.
*13  (xmodel) not found or some unhandled error occured.
*14  (xmodel) not found or some unhandled error occured.
furniture_smallfoldingtable  (xmodel) not found or some unhandled error occured.

furniture_plainchair  (xmodel) not found or some unhandled error occured.
furniture_bookshelves1  (xmodel) not found or some unhandled error occured.
furniture_walltable1  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
furniture_bookshelveswide  (xmodel) not found or some unhandled error occured.
furniture_grandfatherclocktall  (xmodel) not found or some unhandled error occur
ed.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
crate01  (xmodel) not found or some unhandled error occured.
light_lantern_on  (xmodel) not found or some unhandled error occured.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
prop_kitchen_sink01  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangulartall  (xmodel) not found or some unhandled error occured.

prop_kitchen_sink01  (xmodel) not found or some unhandled error occured.
prop_kitchen_faucet01  (xmodel) not found or some unhandled error occured.
prop_metal_pail1  (xmodel) not found or some unhandled error occured.
prop_stove02  (xmodel) not found or some unhandled error occured.
furniture_cabinet  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_pictureframe01  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_tall02  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_tall01  (xmodel) not found or some unhandled error occured.
prop_metal_pail1  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_tinbox_oval_flat  (xmodel) not found or some unhandled error occured.
prop_tinbox_oval_tall  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangularflat01  (xmodel) not found or some unhandled error occure
d.
prop_tinbox_rectangularflat02  (xmodel) not found or some unhandled error occure
d.
prop_tinbox_rectangularflat03  (xmodel) not found or some unhandled error occure
d.
prop_tinbox_rectangulartall  (xmodel) not found or some unhandled error occured.

prop_tinbox_round_flat  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_small  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_small  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_tall01  (xmodel) not found or some unhandled error occured.
prop_diningplate_ovalstack  (xmodel) not found or some unhandled error occured.
prop_diningplate_ovalstack  (xmodel) not found or some unhandled error occured.
prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundplain  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundplain  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundplain  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundplain  (xmodel) not found or some unhandled error occured.

prop_tinbox_rectangulartall  (xmodel) not found or some unhandled error occured.

prop_tinbox_square_tall02  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_tall01  (xmodel) not found or some unhandled error occured.
prop_tinbox_oval_tall  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangularflat03  (xmodel) not found or some unhandled error occure
d.
prop_tinbox_square_small  (xmodel) not found or some unhandled error occured.
prop_diningplate_ovalfloral  (xmodel) not found or some unhandled error occured.

prop_tinbox_oval_flat  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_small  (xmodel) not found or some unhandled error occured.
prop_kitchencopperpan  (xmodel) not found or some unhandled error occured.
prop_kitchencopperpan  (xmodel) not found or some unhandled error occured.
prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_diningplate_roundstack  (xmodel) not found or some unhandled error occured.

prop_metal_pail1  (xmodel) not found or some unhandled error occured.
prop_kitchencopperpan  (xmodel) not found or some unhandled error occured.
prop_kitchencopperpan  (xmodel) not found or some unhandled error occured.
prop_kitchencopperpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpotlid  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpan  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_kitchenmetalpot  (xmodel) not found or some unhandled error occured.
prop_diningplate_ovalstack  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangulartall  (xmodel) not found or some unhandled error occured.

prop_tinbox_square_tall02  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_tall01  (xmodel) not found or some unhandled error occured.
prop_tinbox_oval_tall  (xmodel) not found or some unhandled error occured.
prop_tinbox_oval_tall  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangularflat01  (xmodel) not found or some unhandled error occure
d.
prop_tinbox_square_small  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangulartall  (xmodel) not found or some unhandled error occured.

prop_tinbox_square_tall02  (xmodel) not found or some unhandled error occured.
prop_tinbox_square_tall01  (xmodel) not found or some unhandled error occured.
prop_tinbox_oval_tall  (xmodel) not found or some unhandled error occured.
prop_tinbox_rectangularflat01  (xmodel) not found or some unhandled error occure
d.
prop_tinbox_square_small  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
light_walllightcrystal_off  (xmodel) not found or some unhandled error occured.
furniture_walltable2  (xmodel) not found or some unhandled error occured.
furniture_tableclock1  (xmodel) not found or some unhandled error occured.
furniture_walltable2  (xmodel) not found or some unhandled error occured.
light_lantern_on  (xmodel) not found or some unhandled error occured.
*15  (xmodel) not found or some unhandled error occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
tree_grey_oak_xl_a  (xmodel) not found or some unhandled error occured.
vehicle_tiger_woodland_brush_static  (xmodel) not found or some unhandled error
occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
caen_barbedwire_2  (xmodel) not found or some unhandled error occured.
caen_barbedwire_2  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
caen_barbedwire_2  (xmodel) not found or some unhandled error occured.
caen_barbedwire_2  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
military_hedgehog  (xmodel) not found or some unhandled error occured.
caen_barbedwire_2  (xmodel) not found or some unhandled error occured.
caen_barbedwire_2  (xmodel) not found or some unhandled error occured.
vehicle_panzer_ii_static  (xmodel) not found or some unhandled error occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
*16  (xmodel) not found or some unhandled error occured.
german_artillery_flak88_nm_destroy  (xmodel) not found or some unhandled error o
ccured.
german_artillery_flak88_nm  (xmodel) not found or some unhandled error occured.
fx  (xmodel) not found or some unhandled error occured.
*17  (xmodel) not found or some unhandled error occured.
*18  (xmodel) not found or some unhandled error occured.
*19  (xmodel) not found or some unhandled error occured.
*20  (xmodel) not found or some unhandled error occured.
*21  (xmodel) not found or some unhandled error occured.
*22  (xmodel) not found or some unhandled error occured.
*23  (xmodel) not found or some unhandled error occured.
*24  (xmodel) not found or some unhandled error occured.
*25  (xmodel) not found or some unhandled error occured.
*26  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
prop_wooden_barrel1  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
vehicle_opel_blitz_woodland_static  (xmodel) not found or some unhandled error o
ccured.
prop_wooden_barrel1  (xmodel) not found or some unhandled error occured.
prop_wooden_barrel1  (xmodel) not found or some unhandled error occured.
prop_barrel_black  (xmodel) not found or some unhandled error occured.
*27  (xmodel) not found or some unhandled error occured.
prop_traincar01_opendoor  (xmodel) not found or some unhandled error occured.
prop_woodstack1  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_crate_dak5  (xmodel) not found or some unhandled error occured.
prop_ladder_wood_16_ft_static  (xmodel) not found or some unhandled error occure
d.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
tree_grey_oak_med_a  (xmodel) not found or some unhandled error occured.
caen_bush_full_01  (xmodel) not found or some unhandled error occured.
caen_bush_full_01  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
caen_bush_full_01  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_3  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_2  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
prop_wooden_barrel1  (xmodel) not found or some unhandled error occured.
brush_newgrass_squareclump  (xmodel) not found or some unhandled error occured.
brush_newgrass_triangularclump  (xmodel) not found or some unhandled error occur
ed.
brush_newgrass_triangularclump  (xmodel) not found or some unhandled error occur
ed.
prop_streetlamp_off  (xmodel) not found or some unhandled error occured.
prop_streetlamp_off  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_group_1  (xmodel) not found or some unhandled error occured.
caen_hedge_wall_1  (xmodel) not found or some unhandled error occured.
Finished loading...
`
How can I solve these errors on 2.79 or 2.81? The problem is that my computer can no longer handle win11. Win7 only. That's why I want to use blender up to max 2.81. I just want to put a ladder in a folder. Call of duty 2 folder

**Comment by mauserzjeh** [comment]
Először ki kell szedned minden szükséges fájlt az .iwd fájlokból. Winrar-ral simán meg lehet nyitni az .iwd fájlokat és a lényeg, hogy minden .iwd-ből ki kell szedned a megfelelő mappákat, ahogy a [readme-ben is van](https://github.com/mauserzjeh/cod-asset-importer/blob/master/README.md) (a régi addonnál is így volt, lehet ott a pályáknak az "mp" almappázása hiányzott, erre már nem emlékszem, de pont ezért open source, hogy meg lehessen nézni a kódot vagy esetleg forkolni és módosítani, nekem már nincs időm foglalkozni a régivel, meg teljesítményben sem volt jó, pont ezért írtam újra). Ha rossz a mappaszerkezet akkor eleve nem fogja megtalálni a fájlokat. Lényegében annyi, hogy csinálsz egy mappát ahova majd kicsomagolod a szükséges fájlokat, megnyitod egyesével az .iwd fájlokat és ha olyan mappát találsz ami a readme-ben megvan jelölve az adott játékhoz, akkor fogod és kihúzod az .iwd-ből ebbe a mappába. Ha rákérdez, hogy valamelyik mappa tartalmát össze szeretnéd-e mergelni vagy felülírni az egyező fájlokat akkor nyugodtan írd felül. Ha kiszedtél mindent és a mappaszerkezet is stimmel, akkor jó kell, hogy legyen az import. 

Azt nem tudom, hogy a blender melyik verziója fut-e win7-en, a win11-et pedig nem próbáltam, mert win10-et használok. De tipikusan ha olyan hibát látsz amit írtál az azért van, mert az addon nem találja ott ahol lennie kellene a szükséges fájlnak.

**Comment by tudat-lan** [comment]
Hali ezeket kicsomagoltam : https://www.dropbox.com/scl/fi/lfhfde53rks2ksj6y9v6g/mp_village.iwd?rlkey=nrpapk5b9uhz10xxo62u06z4m&st=ttdugf9d&dl=0
https://www.dropbox.com/scl/fi/ybpzghkewdkoqq2c0gqh6/mp_village_night.iwd?rlkey=qxmdj7d4duh94ykhyh4ci4rtn&st=q1r8c0sm&dl=0
https://www.dropbox.com/scl/fi/kxuynjxgqwcgkzoxapm1d/mp_village_snow.iwd?rlkey=9vow3se3ctrfohggjaw0260bq&st=om05ebt9&dl=0
Itt egy kép is róla mert a d3dbsp-t így tudom csak betallózni:
https://www.dropbox.com/preview/kint.png?context=file_uploader_preview_file&role=personal

**Comment by mauserzjeh** [comment]
Tudsz valami olyan linket küldeni a screenshotról, ahol meg tudom nézni bejelentkezés nélkül? Akár ide is csatolhatod. Másrészt ha jól sejtem csak a pályák .iwd-jeit csomagoltad ki. Minden .iwd-t ki kell csomagolni ami az alapjáték része

**Comment by tudat-lan** [comment]
Igen csak ezt a pályát csomagoltam ki: https://gamebanana.com/mods/459105
![kint](https://github.com/user-attachments/assets/b327b1ec-32b8-4a9c-a667-f6be08ed71ee)
Asztalon csináltam egy village mappát. Az egész cod2 játék alap iwd-t csomagoljam ki valahova? Azt hittem elég az adott map-ot kicsomagolni valahova..

**Comment by mauserzjeh** [comment]
Minden kell, mert a textúrák, xmodellek és minden egyéb az nincs pályánként eltárolva, csak hivatkozik rájuk a fájl. Kell egy közös mappa ahova kihúzol minden szükséges mappát az iwd-kből. Valamint ha kicsomagolsz egy custom mapot tartalmazó iwd-t, mint pl.: az mp_village-t, akkor az abban lévő szükséges mappákat is ebbe a közös mappába rakd.

**Comment by tudat-lan** [comment]
Most is ugyan az.... Pedig. 2.83.9 kicsomagolva: 
![kép](https://github.com/user-attachments/assets/33c0ec45-2cd5-44f8-bfca-5b3158e21b23)
a toujane így tölti be: 
![kép](https://github.com/user-attachments/assets/bc989e97-ea96-48f0-ae3e-8c78e5b66fe0)

**Comment by tudat-lan** [comment]
csinálnál egy videót erről az összes iwd file kibontásról meg hogy megy?

**Comment by mauserzjeh** [comment]
Ne haragudj, de nincs időm ezzel foglalkozni már. Az összes .iwd-t amit a main-ben találsz nyisd meg winrar-al és szedd ki belőle a mappákat egy közös mappába, tehát minden .iwd tartalmát 1 közös mappába, majd onnan importálni a kívánt pályát. A régi pluginnál (ha azt használod) import előtt meg kellett adni azt a mappát is ahova kicsomagoltál mindent, mert ott még nem volt automatikusan ez lekezelve
