### ISSUE TITLE
Blender 3.1 not installing

### ISSUE THREAD

**Issue by GoldenBlack4** [mauserzjeh/cod-asset-importer#2]
I tried to install the plugin on Blender 3.1, but no luck. 
Nothing happen :/

**Comment by mauserzjeh** [comment]
@GoldenBlack4 Hey, can you please tell me the steps how did you try to install the plugin?

I updated the release as it had a .rar file for the plugin which Blender doesn't recognize. There is a .zip now that you can install by clicking on Edit > Preferences > Add-ons > Install and then select the .zip file attached in the release. I just tested it with Blender 3.1 and it installs fine with no errors.

**Comment by GoldenBlack4** [comment]
Hi,

Well I clicked on edit, preferences, addons and I installed it by selecting the .zip as you mention. I tried with every zip, zip-master, even by decompressing the .rar and recompressing it to .zip. 

But if you got it working on Blender 3.1, I should be able to install it too! I will give an other try later.

In fact, plugins are correctly placed inside the blender's plugins folder. But nothing showed up in the import menu...

**Comment by mauserzjeh** [comment]
@GoldenBlack4 Try to uninstall the plugin, open the console by clicking Window > Toggle Console and then reinstall the plugin and see if Blender throws any errors. Also verify that the plugin correctly installed by searching for "Call of Duty Asset Importer" in the search bar on the Add-ons tab

After installing the plugin, don't forget to enable it in the Add-ons menu by ticking that little checkbox. Maybe it is installed correctly and you just forgot to enable it

**Comment by GoldenBlack4** [comment]
I don't know exactly what happened, if you changed something, but I removed every plugins, I redownloaded the new .zip and know it's working!

Thank you again for this tool, really appreciated!

**Comment by mauserzjeh** [comment]
You're welcome :)
