### ISSUE TITLE
Cod2 map stuck on importing

### ISSUE THREAD

**Issue by GoldenBlack4** [mauserzjeh/cod-asset-importer#6]
Hey it's me again.

Thanks for the last update, I can now import without any error for most maps.
Actually, I imported the solo map "Moscow" without any trouble in 5 minutes.
In contrast, I am not able to load duhoc_assault or other heavier maps. The process seems to be stuck at a certain point. I tried multiple times and I let my PC run overnight without success.

Thanks

**Comment by mauserzjeh** [comment]
I encountered the same problem for bigger maps, but eventually they all imported. Blender seems to just hang after a while and it seems like its doing nothing, then starts to import again. Not sure if its the plugin's problem.

I will try to make further optimizations in the code and detect what causes this thing. I have planned to rewrite the plugin again from the ground up in either golang or rust as a python module to have a way better performance.

**Comment by GoldenBlack4** [comment]
[INFO] importer.py:396 Imported xmodel: brush_newgrasstuft_shortwide_lod10 [1.09s]
[INFO] importer.py:396 Imported xmodel: brush_newgrasstuft_tallnarrow_lod10 [1.08s]

It always stops at those lines

**Comment by Hery387** [comment]
Hey, I recently came across this addon, but  I can't even seem to find the folder with the maps/xmodels. May I ask where it is located so that I can test importing the maps to blender?

**Comment by mauserzjeh** [comment]
@Hery387 If you are asking this question regarding cod2, then you will find the necessary folders inside the .iwd files in the "main" folder. Check the readme in the repository.

**Comment by mauserzjeh** [comment]
Hey @GoldenBlack4!

After a long time I had some time to rewrite the plugin for better performance. Check the latest [release](https://github.com/mauserzjeh/cod-asset-importer/releases/tag/v3.0)
